config/routes.rb
Rails.application.routes.draw do
  
  root 'harvesting#select'
  resources :users
  resources :harvesting
  get 'signup', to: 'harvesting#select'
  post 'select', to: 'harvesting#show'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/harvesting_controller.rb
class HarvestingController < ApplicationController

  def index
  end

  def select #Harvest API data and selecting params
  	# @user = User.new
  subdomain = 'safetycheckinc'
	username = 'gscannell@safetycheckinc.com'
	password = 'safetycheck'
	harvest = Harvest.hardy_client(subdomain: subdomain, username: username, password: password)
	@clients = harvest.clients.all
	@projects = harvest.projects.all
	@tasks = harvest.tasks.all
	#getting clients' names and ids in a collection
	client_ID_Table = []
	@clients.each do |c|
	client_ID_Table <<[
	{name: c['name'], id: c['id']},	
	]
	end
	#getting projects' id and corresponding client id in a collection
	project_ID_Table = []
	@projects.each do |c|
		project_ID_Table <<[
		{client_id: c['client_id'], project_id: c['id'] },
		]
	end
	#get task id associated with task name
	task_ID_Table = []
	@tasks.each do |c|
		task_ID_Table <<[
		{task_name: c['name'], task_id: c['id'] },
		]
	end
	#initializing active clients for selection
	@activeclients=[]
	@notactiveclients=[]
		@clients.each do |data|
			if data['active']==true
			@activeclients << data['name']
			else
			@notactiveclients << data['name']
			end
		end
	#initializing active tasks for selection	
	@activetasks=[]
	@notactivetasks=[]
		@tasks.each do |data|
			if data['deactivated']==false
			@activetasks << data['name']
			else
			@notactivetasks << data['name']
			end
		end
  end

  def show #showing the client time data 
  # @user = User.new
  # @user = User.find(params[:client, :task, :start_month, :start_day, :start_year, :end_month, :end_day, :end_year])
	#given user client param find associated client id (testing with param "Windward")
	subdomain = 'safetycheckinc'
	username = 'gscannell@safetycheckinc.com'
	password = 'safetycheck'
	harvest = Harvest.hardy_client(subdomain: subdomain, username: username, password: password)
	@clients = harvest.clients.all
	@projects = harvest.projects.all
	@tasks = harvest.tasks.all

	client_ID_Table = []
	@clients.each do |c|
		client_ID_Table <<[{name: c['name'], id: c['id']}]
	end
	#getting projects' id and corresponding client id in a collection
	project_ID_Table = []
	@projects.each do |c|
		project_ID_Table <<[{client_id: c['client_id'], project_id: c['id'] }]
	end
	#get task id associated with task name
	task_ID_Table = []
	@tasks.each do |c|
		task_ID_Table <<[{task_name: c['name'], task_id: c['id'] }]
	end

	@client_id = {}
	@client_id = client_ID_Table.select{|key, hash| key[:name] == params[:client]}
	@client_id = @client_id[0][0][:id] 
	#get project ids associated with cient id
	@project_ids = {}
	@project_ids = project_ID_Table.select{|key, hash| key[:client_id] == @client_id}
	@project_ids = [@project_ids[1][0][:project_id], @project_ids[0][0][:project_id]]
	#given user task param find assoiated task id (testing with param "inspection") 
	@task_id = {}
	@task_id = task_ID_Table.select{|key, hash| key[:task_name] == params[:task]}
	@task_id = @task_id[0][0][:task_id]
	#given user time params, get time parse for entry call
	@time_start = "#{params[:start_month]}/#{params[:start_day]}/#{params[:start_year]}" #"e.g. 11/22/2015"
	@time_end = "#{params[:end_month]}/#{params[:end_day]}/#{params[:end_year]}"         #"e.g. 11/23/2015"
	#get harvest entries for the two project id indices (field work and office work)
	office_entries = harvest.reports.time_by_project(Harvest::Project.new(id: @project_ids[0]), Time.parse(@time_start), Time.parse(@time_end))
	field_entries = harvest.reports.time_by_project(Harvest::Project.new(id: @project_ids[1]), Time.parse(@time_start), Time.parse(@time_end))
	 #intialize and get total entries and hours 
	@total_entries = 0
	@total_hours = 0
	office_entries.each do |data|
	  if data.task_id == @task_id
	     @total_hours += data.hours
	     @total_entries += 1
	  end
	end
	field_entries.each do |data|
	  if data.task_id == @task_id
	      @total_hours += data.hours
	    	@total_entries += 1
	  end
	end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end

  def create
    # data comes from harvesting#select
  end

  def show
  end

  def edit
  end

  def update
  end

  def login
  end

  def logout
  end

  def authenticate
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/harvesting_helper.rb
module HarvestingHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/harvesting/index.html.erb
<h1>Harvesting#index</h1>
<p>Find me in app/views/harvesting/index.html.erb</p>

app/views/harvesting/select.html.erb
<main class="container">
	<!-- Row of form columns -->
	<section class="row">
		<div class="col-4">
			<h3>Clients</h3>
			<!-- START FORM!!!!!! -->
			<%= form_tag select_path, method: 'post' do %>
    		<select name="client">
    			<% @activeclients.each do |client| %>
					<option value="<%= client %>"><%= client %></option>	
				<% end %>
			</select>
		</div>

		<div class="col-3">
			<h3>Tasks</h3>
    		<select name="task">
				<% @activetasks.each_with_index do |task, i| %>
						<option value="<%= task %>"><%= task %></option>	
				<% end %>
			</select>
		</div>

		<div class="col-5">
			<h3>Start Date &nbsp;&nbsp;&nbsp; End Date</h3>
    		<select name="start_month">
    			<% ['January', 'February', 'March', 'April', 'May','June','July','August','September','October', 'November', 'December'].each_with_index do |month, i| %>
					<option value="<%= i + 1 %>"><%= month %></option>	
				<% end %>
			</select>
			<select name="start_day">
				<% 1.upto(31) do |day| %>
					<option value="<%= day %>"><%= day %></option>	
				<% end %>
			</select>
			<select name="start_year">
				<% ['2013', '2014', '2015'].each do |year| %>
					<option value="<%= year %>"><%= year %></option>	
				<% end %>
			</select>
    		<select name="end_month">
    			<% ['January', 'February', 'March', 'April', 'May','June','July','August','September','October', 'November', 'December'].each_with_index do |month, i| %>
					<option value="<%= i + 1 %>"><%= month %></option>	
				<% end %>
			</select>
			<select name="end_day">
				<% 1.upto(31) do |day| %>
					<option value="<%= day %>"><%= day %></option>	
				<% end %>
			</select>
			<select name="end_year">
				<% ['2013', '2014', '2015'].each_with_index do |year, i| %>
					<option value="<%= year %>"><%= year %></option>	
				<% end %>
			</select>
			<%= submit_tag "Results" %>
    		<% end %>
    		<!-- END FORM!!!!!! -->
		</div>
	</section>
</main>

app/views/harvesting/show.html.erb
<main class="container">
  <section class="row-2">
    <div class="col-6 push-3">
      <h2 class="centered-text">Results</h2>
      <h2><%= @total_hours.round(0) %><h2><h2> Total Hours </h2>
      <h2><%= @total_entries %><h2><h2> Total Entries </h2>
    </div>
  </section>
</main>

app/views/home/index.html.erb
<main class="container">
  <section class="row">
    <div class="col-6 push-3 centered-text">
      <h2>Safety Check Harvest Time</h2>
      <p>Choose a client to view service </p>
    </div>
  </section>
</main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SCI Harvest Time!</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <link rel='stylesheet' href='https://fonts.googleapis.com/css?family=Lato:400,300,700|Source+Code+Pro:400,700' />
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<header class="container">
  <div class="row-loose">
    <div class="col-12">
      <h1 class="centered-text">
        <%= link_to 'SCI Harvest Time!', root_path %>
      </h1>
</header>
<%= yield %>

</body>
</html>

app/views/users/authenticate.html.erb
<h1>Users#authenticate</h1>
<p>Find me in app/views/users/authenticate.html.erb</p>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/login.html.erb
<h1>Users#login</h1>
<p>Find me in app/views/users/login.html.erb</p>

app/views/users/logout.html.erb
<h1>Users#logout</h1>
<p>Find me in app/views/users/logout.html.erb</p>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>